### ISSUE TITLE
Test Samples workflow Failure - Bicep Version Mismatch

### ISSUE THREAD

**Issue by kachawla** [radius-project/samples#1767]
## Bug information

The target for `Test Samples` workflow is release branch, however looks like we are now always pulling edge version of bicep, which is causing the workflow to fail if backwards incompatible schema changes are pushed to edge.

```
 env:
    RUN_IDENTIFIER: samplestest-10719914389-2
    BRANCH: v0.37
    GH_TOKEN: ***
    AZURE_LOCATION: westus3
    AWS_REGION: us-west-2
    AWS_ZONES: us-west-2a,us-west-2b,us-west-2c
Downloading Bicep for channel edge...
Building ./samples/eshop/eshop.bicep...
```

Link to failed test run: https://github.com/radius-project/samples/actions/runs/10719914389/job/29805053037

### Steps to reproduce (required)
Re-run any test samples workflow: https://github.com/radius-project/samples/issues?q=is%3Aopen+is%3Aissue+label%3Atest-failure

### Observed behavior (required)

`Test Samples` workflow is failing.

### Desired behavior (required)

The workflow should pass.

## Additional context

[AB#13164](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13164)
